name: 'Cache Anything New'
author: 'Israel Roldan <israel.alberto.rv@gmail.com>'
description: >-
  Catch a series of commands then it will check for the new files generated and it should cache those.

inputs:
  script:
    description: 'Bash script which will be executed and cached.'
    required: true
  is_cached:
    description: 'Boolean value to check if the key is cached.'
    required: true
  cache:
    description: 'Path of the cache directory.'
    required: false
    default: 'cache-directory'
  snapshot:
    description: 'The snapshot will be created from this path, recommended the main path (/).'
    required: false
    default: '/'
  exclude:
    description: 'Exclude directories and files from the indexation. Separate with spaces ( ).'
    required: false
    default: '/boot /data /dev /mnt /proc /run /sys'

runs:
  using: 'composite'
  steps:
    - env:
        ENV_IS_CACHED: ${{ inputs.is_cached }}
        ENV_RUNNER_TEMP: ${{ runner.temp }}
        ENV_CACHE: ${{ runner.temp }}/${{ inputs.cache }}
        ENV_SCRIPT_BASE: ${{ github.workspace }}/.github/workflows
        ENV_SCRIPT: ${{ github.workspace }}/.github/workflows/${{ inputs.script }}
        ENV_SNAPSHOT: ${{ inputs.snapshot }}
        ENV_EXCLUDE: ${{ inputs.exclude }}
      run: ${GITHUB_ACTION_PATH}/src/init.sh
      shell: bash

branding:
  color: 'orange'
  icon: 'archive'
