name: 'Cache Anything New'
author: 'Israel Roldan <israel.alberto.rv@gmail.com>'
description: >-
  Catch a series of commands then it will check for the new files generated and it should cache those.
inputs:
  id:
    description: 'Unique alias to identify this cache.'
    required: false
    default: 'cache-anything-new'
  version:
    description: 'The version is an easy way to create a new cache or come back to a previous.'
    required: false
    default: 'v1.0'
  directory:
    description: 'Path of the directory, recommended the main path (/).'
    required: false
    default: '/'
  exclude:
    description: 'Exclude directories and files from the indexation. Separate with spaces ( ).'
    required: false
    default: '/boot /data /dev /mnt /proc /run /sys'
runs:
  using: 'composite'
  steps:
    - run: |
        set -xv
        echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
        echo "inputs.id: ${{ inputs.id }}"
        echo "inputs.version: ${{ inputs.version }}"
        echo "inputs.directory: ${{ inputs.directory }}"
        echo "inputs.exclude: ${{ inputs.exclude }}"
        EXCLUDED=( ${{ inputs.exclude }} )
        for EXCLUDE in ${EXCLUDED}
        do
          echo "EXCLUDE: ${EXCLUDE}"
          eval "ls -lha ${EXCLUDE}"
        done
        #sudo find \
        #        ${{ inputs.directory }}" \
        #        -type f,l \
        #        -not \( -path "/sys*" -prune \) \
        #        > ${{ runner.temp }}/system_files_snapshot_01.txt \
        #        2> /dev/null || true
        #sudo find / -type f,l > ${{ runner.temp }}/system_files.txt 2> /dev/null || true
      shell: bash
branding:
  color: 'orange'
  icon: 'archive'
