name: 'Cache Anything New'
author: 'Israel Roldan <israel.alberto.rv@gmail.com>'
description: >-
  Catch a series of commands then it will check for the new files generated and it should cache those.
inputs:
  identifier:
    description: 'Unique alias to identify this cache.'
    required: false
    default: 'cache-anything-new'
  version:
    description: 'The version is an easy way to create a new cache or come back to a previous.'
    required: false
    default: 'v1.0'
  directory:
    description: 'Path of the directory, recommended the main path (/).'
    required: false
    default: '/'
  exclude:
    description: 'Exclude directories and files from the indexation. Separate with spaces ( ).'
    required: false
    default: '/boot /data /dev /mnt /proc /run /sys'
runs:
  using: 'composite'
  steps:
    - env:
        ENV_RUNNER_TEMP: ${{ runner.temp }}
        ENV_IDENTIFIER: ${{ inputs.identifier }}
        ENV_VERSION: ${{ inputs.version }}
        ENV_DIRECTORY: ${{ inputs.directory }}
        ENV_EXCLUDE: ${{ inputs.exclude }}
      run: |
        pwd
        ls -lhaR "${GITHUB_ACTION_PATH}"
        echo "ENV_IDENTIFIER: ${ENV_IDENTIFIER}"
        echo "ENV_VERSION:    ${ENV_VERSION}   "
        echo "ENV_DIRECTORY:  ${ENV_DIRECTORY} "
        echo "ENV_EXCLUDE:    ${ENV_EXCLUDE}   "
        "${GITHUB_ACTION_PATH}"/snapshot_start.sh
      shell: bash
branding:
  color: 'orange'
  icon: 'archive'
