name: 'Cache Anything New'
author: 'Israel Roldan <israel.alberto.rv@gmail.com>'
description: >-
  Catch a series of commands then it will check for the new files generated and it should cache those.
inputs:
  id:
    description: 'Unique alias to identify this cache.'
    required: false
    default: 'cache-anything-new'
  version:
    description: 'The version is an easy way to create a new cache or come back to a previous.'
    required: false
    default: 'v1.0'
  include:
    description: 'Include directories and files from the indexation. Separate with semi-colon (;).'
    required: false
    default: '/etc;/usr;/var;'
  exclude:
    description: 'Exclude directories and files from the indexation. Separate with semi-colon (;).'
    required: false
    default: '/sys;/proc;/mnt;/dev;/run;/etc/mtab;/var/cache/apt/archives;/tmp;/var/tmp;/var/backups;/boot;/vmlinuz;'
runs:
  using: 'composite'
  steps:
    - run: |
        set -xv
        echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
        echo "inputs.id: ${{ inputs.id }}"
        echo "inputs.version: ${{ inputs.version }}"
        echo "inputs.exclude: ${{ inputs.exclude }}"
        sudo ls -lha /
        sudo du -h -d 3 / > ${{ runner.temp }}/system_files_size.txt 2> /dev/null || true
        sudo find / -type f,l > ${{ runner.temp }}/system_files.txt 2> /dev/null || true
      shell: bash
branding:
  color: 'orange'
  icon: 'archive'
